Adds unit test for a stationary, contacting configuration.
edrumwri/drake pull request #18
Opened 2019-05-31 16:47 UTC by mws262

Test for ComputeActuationForContactDesired to point out missing gravity compensation. Also added a test for ComputeActuationForContactNotDesired, but it is mostly a placeholder. Currently there are errors in ComputeActuationForContactNotDesired which need to be resolved.

2019-05-31 17:41 UTC, edrumwri approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/18)* status: all files reviewed, 1 unresolved discussion (waiting on @mws262)

___
*[examples/iiwa_soccer/box_controller_test.py, line 114 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgDxkhG6InNNUMij8zu:-LgDxkhG6InNNUMij8zv:b6m7ph1) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L114)):*
> ```Python
>         logging.info('  Normal (pointing to ' + body_A.name() + '): ' + str(i.nhat_BA_W))
> 
>     # Tests that ComputeActuationForContactDesired produces forces which keep the box stationary when given a plan
> ```

Nit recommend "when given a plan that is already satisfied" -> "when the planned position and velocity for the box matches the current position and velocity for the box"
___
*[examples/iiwa_soccer/box_controller_test.py, line 119 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgDyCJ824eACAKC_DTV:-LgDyCJ824eACAKC_DTW:bvk2o5a) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L119)):*
> ```Python
>         box_height = 0.4
>         ball_radius = 0.1
>         ball_mass = 1
> ```

FYI Not saying that you should do this since this is research quality code, but getting the ball mass and gravitational acceleration out of the MultibodyPlant is safer.


<!-- Sent from Reviewable.io -->

2019-06-01 16:31 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @mws262)

___
*[examples/iiwa_soccer/box_controller_test.py, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgIsCRP78QShp55LNBf:-LgIsCRP78QShp55LNBg:b-e6w0mf) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L134)):*
> ```Python
> 
>         # Actuation for the box should only be gravity compensation.
>         force = self.controller.ComputeActuationForContactDesired(self.context, q0, v0, q_robot_planned, v_robot_planned,
> ```

This (and in test_ComputeActuationForContactNotDesired()) fails hard because it should be passed self.controller_context rather than self.context. I blame Drake- it should be able to know when it's passed a Context that does not correspond to the proper System.


<!-- Sent from Reviewable.io -->

2019-06-01 17:19 UTC, mws262 reviewed
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/18)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @edrumwri)

___
*[examples/iiwa_soccer/box_controller_test.py, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgIsCRP78QShp55LNBf:-LgJ0HpX4C3uEmBMCfeE:b-padk4o) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L134)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This (and in test_ComputeActuationForContactNotDesired()) fails hard because it should be passed self.controller_context rather than self.context. I blame Drake- it should be able to know when it's passed a Context that does not correspond to the proper System.
</blockquote></details>

Thanks -- fixed this. It still seems to be erroring out for me though.


<!-- Sent from Reviewable.io -->

2019-06-01 17:19 UTC, mws262 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/18#-:-LgJ2Oe60-FPR7m5CIeJ:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @edrumwri)



<!-- Sent from Reviewable.io -->

2019-06-01 18:31 UTC, edrumwri requested changes
I've noted a few more changes necessary for this test to pass (once you merge in the corrections to my branch that this test helped me identify).

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/18#-:-LgJEpsnAXn78wN4IYWB:b-j5bmwv)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @edrumwri and @mws262)

___
*[examples/iiwa_soccer/box_controller_test.py, line 119 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgJEBsG2ECv8dzWCbw7:-LgJEBsG2ECv8dzWCbw8:b4ik0th) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L119)):*
> ```Python
>         box_height = 0.4
>         ball_radius = 0.1
>         ball_mass = 1
> ```

This should be `box_mass`
___
*[examples/iiwa_soccer/box_controller_test.py, line 122 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgJEEVs1u1HqWK2Gwty:-LgJEEVs1u1HqWK2Gwtz:b-fiq3a5) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L122)):*
> ```Python
>         gravity = -9.81
> 
>         # Initial configuration is no rotation for ball and box. Box is `kissing' the top of the ball.
> ```

The controller uses a concept of a "desired" signed distance under contact, which should generally be negative, since Drake uses penalty method type contacts. You can get that using:

`eps = self.controller.get_desired_ball_signed_distance_under_contact()` 
___
*[examples/iiwa_soccer/box_controller_test.py, line 123 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgJEXbQ1NlWYxlrgGo6:-LgJEXbQ1NlWYxlrgGo7:bgiormo) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L123)):*
> ```Python
> 
>         # Initial configuration is no rotation for ball and box. Box is `kissing' the top of the ball.
>         q0 = np.array([0, 0, 0, 1, 0, 0, ball_radius * 2 + box_height/2,
> ```

Then the last term of this should be `eps + ball_radius * 2 + box_height/2`.
___
*[examples/iiwa_soccer/box_controller_test.py, line 146 at r1](https://reviewable.io/reviews/edrumwri/drake/18#-LgJEiHN9z4qvtci8ue9:-LgJEiHN9z4qvtci8ueA:byehmuf) ([raw file](https://github.com/edrumwri/drake/blob/7e87db58f3ca35e16a58a469a65a5e15025ac845/examples/iiwa_soccer/box_controller_test.py#L146)):*
> ```Python
>         # 1. Get rid of 'v_from_ball_position_tracking' in the vdot calculation.
>         # 2. Add np.reshape([0,0,0,0,0,9.81], [6,1]) to vdot.
>         self.assertAlmostEqual(force[5], -ball_mass * gravity, msg="z force should counteract gravity and no more. Was: " + str(force[5]), delta=1e-12)
> ```

Replace `ball_mass` here with `box_mass`.


<!-- Sent from Reviewable.io -->

2020-10-27 18:51 UTC, closed without merging